<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

	<title>blog, blog...</title>

	<!-- META -->
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="robots" content="index, follow" />
	<meta name="description" content="Offering the gentlemen of the internet a one-stop-shop for all things current, noteworthy and down-right cool." />
	<meta name="author" content="Human Binary" />
	<meta name="copyright" content="Copyright 2012" />

	<!-- SITE ICONS -->
	<link rel="shortcut icon" type="image/x-icon" href="http://www.internetgentleman.com/favicon.ico">
	<link rel="shortcut icon" type="image/x-icon" href="http://www.internetgentleman.com/wp-content/themes/ig/images/favicon.ico" />
	<link rel="apple-touch-icon" href="http://www.internetgentleman.com/wp-content/themes/ig/images/touch_icon.png" />

	<!-- FEED -->
	<link rel="alternate" type="application/rss+xml" title="Internet Gentleman" href="http://feeds.feedburner.com/InternetGentleman" />




	<!-- CSS -->
	<link rel="stylesheet" href="http://www.internetgentleman.com/wp-content/themes/ig/css/screen.css?time=1201091246PM" media="screen,projection" type="text/css" />
	<link rel="stylesheet" href="http://www.internetgentleman.com/wp-content/themes/ig/css/print.css" media="print" type="text/css" />



	<link rel='stylesheet' id='wp-pagenavi-css'  href='http://www.internetgentleman.com/wp-content/plugins/wp-pagenavi/pagenavi-css.css?ver=2.50' type='text/css' media='all' />

<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.internetgentleman.com/xmlrpc.php?rsd" />

<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.internetgentleman.com/wp-includes/wlwmanifest.xml" />
<link rel='index' title='Internet Gentleman' href='http://www.internetgentleman.com' />

<meta name="generator" content="WordPress 2.9" />

	<!-- Generated by Simple Tags 1.7.1-rc1.2 - http://wordpress.org/extend/plugins/simple-tags -->
	<meta name="keywords" content="Featured, Video Games, Watch, Shirt" />

	<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-27187069-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

</head>










<body>


<div id="hbnetwork">
	<div id="interior">
	<h4><a class="hb" href="http://www.humanbinary.com" title="Human Binary"><span class="h">H</span><span class="u">u</span><span class="m">m</span><span class="a">a</span><span class="n">n</span> Binary</a> <span>Network</span></h4>
	<ul>
		<li><a class="active" href="http://www.internetgentleman.com" title="Internet Gentleman">Internet Gentleman</a></li>
		<li><a href="http://www.macalicious.com" title="Macalicious">Macalicious</a></li>
	</ul>

	 <div class="clear"> </div>

	</div> <!-- END #INTERIOR -->
</div> <!-- END HBNETWORK -->
	<div id="wrap">

		<div id="header">
	<h2><a href="http://www.internetgentleman.com"><span>Internet Gentleman</span></a></h2>

	<div class="bannerad">
		<a href="http://click.linksynergy.com/fs-bin/click?id=0nSC8lylzts&offerid=146261.10005608&type=4&subid=0">
			<img alt="InglouriousBasterds" border="0" src="http://images.apple.com/itunesaffiliates/US/2009/12/03/InglouriousBasterds_468x60.jpg">
		</a>
		<!--<a href="http://click.linksynergy.com/fs-bin/click?id=0nSC8lylzts&offerid=146261.10004895&type=4&subid=0">
			<img alt="Apple iTunes" border="0" src="http://images.apple.com/itunesaffiliates/US/2009/08/03/TheWalkmen_468x60.jpg" />
		</a>-->
	</div> <!-- END .BANNERAD -->

</div> <!-- END HEADER -->

<div id="navigation">

	<ul id="global">
	<li class="all"><a class="active" href="http://www.internetgentleman.com/"><span>All</span></a></li>
	<li class="entertainment"><a href="http://www.internetgentleman.com/entertainment/"><span>Entertainment</span></a></li>
	<li class="libations"><a href="http://www.internetgentleman.com/libations/"><span>Libations</span></a></li>
	<li class="pad"><a href="http://www.internetgentleman.com/pad/"><span>Pad</span></a></li>
	<li class="style"><a href="http://www.internetgentleman.com/style/"><span>Style</span></a></li>
	<li class="tech"><a href="http://www.internetgentleman.com/tech/"><span>Tech</span></a></li>
	<li class="whips"><a href="http://www.internetgentleman.com/whips/"><span>Whips</span></a></li>
</ul>
	<div id="search">
		<label><span>Search:</span></label>
		<form id="searchform" method="get" action="http://www.internetgentleman.com/index.php">
			<div>
				<input type="text" name="s" id="s" size="15" value=""/>
			</div>
		</form>
	</div> <!-- END #SEARCH -->

</div> <!-- END #NAVIGATION -->


		<div class="clear"> </div>

<div id="content">

	<div id="contentwrap">

		<div id="primary">
			<div id="primaryheader">
				<h3 class="latest"><span>Latest &amp; Greatest</span></h3>
			</div> <!-- END #PRIMARYHEADER -->

			<div id="primaryarticles">


				<div class="article home">
					<div class="postimage">
						<a class="postimage" href="http://www.internetgentleman.com/style/lunatik-multi-touch-watch/" title="LunaTik Multi-Touch Watch">
							<img src="/slir/w220-h220-c1:1/wp-content/themes/ig/images/postpics/img_post_lunatik.jpg" alt="LunaTik Multi-Touch Watch" />
						</a>

						<a class="comments" href="http://www.internetgentleman.com/style/lunatik-multi-touch-watch/#comments" title="1 comment">1 comment</a>
					</div> <!-- END .POSTIMAGE -->

					<div class="posttext">
						<h3><a href="http://www.internetgentleman.com/style/lunatik-multi-touch-watch/" title="LunaTik Multi-Touch Watch">LunaTik Multi-Touch Watch</a></h3>

						<p>The <a href="http://www.kickstarter.com/projects/1104350651/tiktok-lunatik-multi-touch-watch-kits">LunaTik</a> watch band transforms your iPod Nano into the world&#8217;s coolest multi-touch watch. The idea seemed obvious when the new iPod Nano was announced, but to pull this off, you&#8217;d need to match the impecable craftsmanship that Apple is known for. The LunaTik is designed to be a premium conversion kit for someone who wants to dedicate their Nano to being the greatest conversation starter on anyone&#8217;s wrist.</p>

						<p><a class="price" href="http://www.kickstarter.com/projects/1104350651/tiktok-lunatik-multi-touch-watch-kits" title="">$50</a> Find more in <a href="http://www.internetgentleman.com/style/" title="View all posts in Style" rel="category tag">Style</a></p>
					</div> <!-- END .POSTTEXT -->

				</div> <!-- END .ARTICLE -->


				<div class="article home">
					<div class="postimage">
						<a class="postimage" href="http://www.internetgentleman.com/entertainment/god-of-war-iii/" title="God of War III">
							<img src="/slir/w220-h220-c1:1/wp-content/themes/ig/images/postpics/img_post_gow3.jpg" alt="God of War III" />
						</a>

						<a class="comments" href="http://www.internetgentleman.com/entertainment/god-of-war-iii/#comments" title="0 comments">0 comments</a>
					</div> <!-- END .POSTIMAGE -->

					<div class="posttext">
						<h3><a href="http://www.internetgentleman.com/entertainment/god-of-war-iii/" title="God of War III">God of War III</a></h3>

						<p>God of War III is a single player action game, exclusive to the PlayStation 3, and the final installment of the God of War trilogy. Containing signature and addictive God of War game play — a combination of over-the-top action combat, exploration and puzzle-solving — along with an engrossing mythologically inspired storyline and a selection of new weapons and a new weapons system, it is a fitting conclusion to the much praised God of War franchise.</p>

						<p><a class="price" href="http://www.amazon.com/gp/product/B002VFPHKA?ie=UTF8&tag=humabina-20&linkCode=as2&camp=1789&creative=390957&creativeASIN=B002VFPHKA" title="">$49.99</a> Find more in <a href="http://www.internetgentleman.com/entertainment/" title="View all posts in Entertainment" rel="category tag">Entertainment</a></p>
					</div> <!-- END .POSTTEXT -->

				</div> <!-- END .ARTICLE -->


				<div class="article home">
					<div class="postimage">
						<a class="postimage" href="http://www.internetgentleman.com/tech/yellow-j2-premium-noise-isolating-earbuds/" title="Yellow J2 Premium Noise Isolating Earbuds">
							<img src="/slir/w220-h220-c1:1/wp-content/themes/ig/images/postpics/img_post_j2earbuds.jpg" alt="Yellow J2 Premium Noise Isolating Earbuds" />
						</a>

						<a class="comments" href="http://www.internetgentleman.com/tech/yellow-j2-premium-noise-isolating-earbuds/#comments" title="1 comment">1 comment</a>
					</div> <!-- END .POSTIMAGE -->

					<div class="posttext">
						<h3><a href="http://www.internetgentleman.com/tech/yellow-j2-premium-noise-isolating-earbuds/" title="Yellow J2 Premium Noise Isolating Earbuds">Yellow J2 Premium Noise Isolating Earbuds</a></h3>

						<p>If you&#8217;re in the market for a new pair of earbuds, it&#8217;s going to be hard to look past these <a href="http://www.amazon.com/gp/product/B001GS8G0Q?ie=UTF8&#038;tag=humabina-20&#038;linkCode=as2&#038;camp=1789&#038;creative=390957&#038;creativeASIN=B001GS8G0Q">yellow J2 Premium Hi-FI Noise Isolating Earbuds</a> by Jbuds. These colorful buds boast premium sound quality, compact size and a comfortable buds that product rich and dynamic sound no matter what you&#8217;re listening to.</p>

						<p><a class="price" href="http://www.amazon.com/gp/product/B001GS8G0Q?ie=UTF8&tag=humabina-20&linkCode=as2&camp=1789&creative=390957&creativeASIN=B001GS8G0Q" title="">$14.32</a> Find more in <a href="http://www.internetgentleman.com/tech/" title="View all posts in Tech" rel="category tag">Tech</a></p>
					</div> <!-- END .POSTTEXT -->

				</div> <!-- END .ARTICLE -->


				<div class="article home">
					<div class="postimage">
						<a class="postimage" href="http://www.internetgentleman.com/style/efx-darth-vader-concept-helmet/" title="eFX Darth Vader Concept Helmet">
							<img src="/slir/w220-h220-c1:1/wp-content/themes/ig/images/postpics/img_post_vaderconcept.jpg" alt="eFX Darth Vader Concept Helmet" />
						</a>

						<a class="comments" href="http://www.internetgentleman.com/style/efx-darth-vader-concept-helmet/#comments" title="0 comments">0 comments</a>
					</div> <!-- END .POSTIMAGE -->

					<div class="posttext">
						<h3><a href="http://www.internetgentleman.com/style/efx-darth-vader-concept-helmet/" title="eFX Darth Vader Concept Helmet">eFX Darth Vader Concept Helmet</a></h3>

						<p>This incredible looking Darth Vader Concept Helmet is based on pre-production sketches by <a href="http://en.wikipedia.org/wiki/Ralph_McQuarrie">Ralph McQuarrie</a>, the illustrator who designed all of the artwork for the original Star Wars trilogy. The <strong>&#8220;McVader&#8221;</strong> as it&#8217;s known around the <a href="http://www.efxcollectibles.com/p-43-bringing-the-art-off-the-page.aspx">eFX Inc.</a> camp will be available worldwide with quantities limited to just 250 helmets.</p>

						<p><a class="price" href="http://www.efxcollectibles.com/p-43-bringing-the-art-off-the-page.aspx" title="">$899</a> Find more in <a href="http://www.internetgentleman.com/style/" title="View all posts in Style" rel="category tag">Style</a></p>
					</div> <!-- END .POSTTEXT -->

				</div> <!-- END .ARTICLE -->


				<div class="article home">
					<div class="postimage">
						<a class="postimage" href="http://www.internetgentleman.com/pad/deskology-4-piece-desk-set/" title="Deskology 4-piece desk set">
							<img src="/slir/w220-h220-c1:1/wp-content/themes/ig/images/postpics/img_post_deskset.jpg" alt="Deskology 4-piece desk set" />
						</a>

						<a class="comments" href="http://www.internetgentleman.com/pad/deskology-4-piece-desk-set/#comments" title="0 comments">0 comments</a>
					</div> <!-- END .POSTIMAGE -->

					<div class="posttext">
						<h3><a href="http://www.internetgentleman.com/pad/deskology-4-piece-desk-set/" title="Deskology 4-piece desk set">Deskology 4-piece desk set</a></h3>

						<p>Talk about a product just itching to sit next to your Mac. This stunnung <a href="http://www.deskology.com/products-page/desk-sets/desk-set-professional/">4-piece desk set</a> by Deskology is constructed of 3/16&#8243; thick anodized aluminum material. The finish is exactly that of Apple&#8217;s new iMacs and LED Cinema Displays, giving your computer hardware the perfect desk compliment. The set includes an inbox, pencil cup, doodad cup and a business card holder.</p>

						<p><a class="price" href="http://www.deskology.com/products-page/desk-sets/desk-set-professional/" title="">$189</a> Find more in <a href="http://www.internetgentleman.com/pad/" title="View all posts in Pad" rel="category tag">Pad</a></p>
					</div> <!-- END .POSTTEXT -->

				</div> <!-- END .ARTICLE -->


			</div> <!-- END #PRIMARYARTICLES -->

		</div> <!-- END #PRIMARY -->

		<div id="secondary">

	<div id="secondarywrap">

		<div id="twitter">
			<a href="http://twitter.com/netgent" title="@netgent"><span>Follow us on Twitter</span></a>
		</div> <!-- END #TWITTER -->

		<div id="newsletter">
			<p>Stay current, find the freshest deals. <strong>Get the IG Newsletter!</strong></p>


			<form method="post" action="http://www.aweber.com/scripts/addlead.pl">
				<input type="hidden" name="meta_web_form_id" value="1137148612">
				<input type="hidden" name="meta_split_id" value="">
				<input type="hidden" name="unit" value="netgent">
				<input type="hidden" name="redirect" value="http://www.aweber.com/form/thankyou_vo.html" id="redirect_324fcae8972f2f013e4e58d7e7d680ed">
				<input type="hidden" name="meta_redirect_onlist" value="">
				<input type="hidden" name="meta_adtracking" value="">
				<input type="hidden" name="meta_message" value="1">
				<input type="hidden" name="meta_required" value="from">
				<input type="hidden" name="meta_forward_vars" value="0">

				<label for="address">Enter Email Address</label>
				<input type="text" name="from" id="emailaddress">
				<input class="newssubmit" type="image" src="http://www.internetgentleman.com/wp-content/themes/ig/images/blank.gif" value="Go!" />
			</form>

			<!--
			<form>
				<label for="address">Enter Email Address</label>
				<input type="text" name="address" id="emailaddress" />
				<input class="newssubmit" type="image" src="http://www.internetgentleman.com/wp-content/themes/ig/images/blank.gif" value="Go!" />
			</form>
			-->
		</div> <!-- END #NEWSLETTER -->

		<div id="adblocks" class="clear">
			<div class="topleft">
				<a href="http://click.linksynergy.com/fs-bin/click?id=0nSC8lylzts&offerid=146261.10004881&type=4&subid=0">
					<img alt="Apple iTunes" src="http://images.apple.com/itunesaffiliates/US/2009/08/03/MadMen_125x125.jpg">
				</a>
			</div> <!-- END TOPLEFT -->

			<div class="topright">
        		<a href="http://clickserve.cc-dt.com/link/tplclick?lid=41000000028001195&pubid=21000000000227887">
					<img src="http://clickserve.cc-dt.com/link/tplimage?lid=41000000028001195&pubid=21000000000227887" alt="Booty Fruit 125X125">
				</a>
			</div> <!-- END TOPRIGHT -->

			<div class="btmleft">
        		<a href="http://clickserve.cc-dt.com/link/tplclick?lid=41000000028149934&pubid=21000000000227887">
	<img src="http://clickserve.cc-dt.com/link/tplimage?lid=41000000028149934&pubid=21000000000227887" alt="HDTV - Static - 125x125 - Banner">
				</a>
			</div> <!-- END BTMLEFT -->

			<div class="btmright">
				<a href="http://www.internetgentleman.com/advertise/" title="Ad Block 4">
					<img src="http://www.internetgentleman.com/wp-content/themes/ig/images/ads/img_advertise.gif" width="125" height="125" alt="Ad Block 4" />
				</a>
			</div> <!-- END BTMRIGHT -->

		</div> <!-- END #ADBLOCKS -->

		<div id="recentcomments">
			<h4><span>Recent Comments</span></h4>
						<ul>	<li><a href="http://www.internetgentleman.com/pad/xbox-360-curve-tower-gaming-station/#comment-1269" title="Xbox 360 Curve Tower Gaming Station, October 16, 2009">Matt</a>: great site</li>
	<li><a href="http://www.internetgentleman.com/style/lunatik-multi-touch-watch/#comment-930" title="LunaTik Multi-Touch Watch, December 14, 2010">mld</a>: horray, a watch that isnt waterproof and scratches as easily as an ipod! technology for the...</li>
	<li><a href="http://www.internetgentleman.com/entertainment/han-solo-carbonite-desk/#comment-644" title="Han Solo Carbonite Desk, November 18, 2009">jonathan</a>: That scene isn&#8217;t from &#8220;A New Hope&#8221;, it&#8217;s from the end of...</li>
	<li><a href="http://www.internetgentleman.com/tech/yellow-j2-premium-noise-isolating-earbuds/#comment-342" title="Yellow J2 Premium Noise Isolating Earbuds, March 1, 2010">Jason Williams</a>: I can vouch for these headphones, they&#8217;re really great. The price on Amazon...</li>
	<li><a href="http://www.internetgentleman.com/entertainment/late-night-with-the-roots-mixtape/#comment-341" title="Late Night with The Roots Mixtape, January 9, 2010">sam</a>: where is the download button then ?</li>
	<li><a href="http://www.internetgentleman.com/entertainment/late-night-with-the-roots-mixtape/#comment-320" title="Late Night with The Roots Mixtape, January 9, 2010">thor</a>: Cant download it, its been removed :(</li>
</ul>
					</div> <!-- END #RECENTCOMMENTS -->

		<div id="sponsoredlinks">
			<h4><span>Sponsored Links</span></h4>

			<span id="sponsoredads">
				<script type="text/javascript"><!--
				google_ad_client = "pub-5788258272932426";
				/* IG - Sitewide, Sidebar Block 250x250 */
				google_ad_slot = "7862808941";
				google_ad_width = 250;
				google_ad_height = 250;
				//-->
				</script>
				<script type="text/javascript"
				src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</span>
		</div> <!-- END #SPONSOREDLINKS -->

	</div> <!-- END #SECONDARYWRAP -->

</div> <!-- END #SECONDARY -->
		<div id="pagination" class="clear">
		<div class="wp-pagenavi">
<span class="pages">Page 1 of 10</span><span class="current">1</span><a href="http://www.internetgentleman.com/page/2/" class="page" title="2">2</a><a href="http://www.internetgentleman.com/page/3/" class="page" title="3">3</a><a href="http://www.internetgentleman.com/page/4/" class="page" title="4">4</a><a href="http://www.internetgentleman.com/page/5/" class="page" title="5">5</a><a href="http://www.internetgentleman.com/page/6/" class="page" title="6">6</a><a href="http://www.internetgentleman.com/page/7/" class="page" title="7">7</a><a href="http://www.internetgentleman.com/page/8/" class="page" title="8">8</a><a href="http://www.internetgentleman.com/page/9/" class="page" title="9">9</a><a href="http://www.internetgentleman.com/page/2/" >Next</a><a href="http://www.internetgentleman.com/page/10/" class="last" title="Last">Last</a></div>

		<a class="archives" href="http://www.internetgentleman.com/archives" title="IG Archives"><span>View All Archives</span></a>

		</div> <!-- END #PAGINATION -->

	</div> <!-- END #CONTENTWRAP -->

</div> <!-- END #CONTENT -->
		<div id="recommended" class="clear">

	<div id="rectop">

		<h3><span>The Gentleman Also Recommends&hellip;</span></h3>
		<div class="recommendedarchives">
			<a class="recarchives" href="http://www.internetgentleman.com/recommended/" title="See All"><span>See All</span></a>
		</div> <!-- END .RECOMMENDEDARCHIVES -->
	</div> <!-- END #RECTOP -->

	<div id="recbox">

		<div class="recarticle hover">
			<a class="reccomments" href="http://www.internetgentleman.com/entertainment/mighty-muggs/#comments" title="2 comments">2</a>

			<div class="title">
				<h3><a href="http://www.internetgentleman.com/entertainment/mighty-muggs/" title="Mighty Muggs">Mighty Muggs</a></h3>
			</div> <!-- END .TITLE -->

			<img src="/slir/w220-h280-c6:7/wp-content/themes/ig/images/postpics/img_post_mightymuggs.jpg" alt="Mighty Muggs" />
		</div> <!-- END .RECARTICLE -->


		<div class="recarticle hover">
			<a class="reccomments" href="http://www.internetgentleman.com/style/the-newton/#comments" title="0 comments">0</a>

			<div class="title">
				<h3><a href="http://www.internetgentleman.com/style/the-newton/" title="The Newton">The Newton</a></h3>
			</div> <!-- END .TITLE -->

			<img src="/slir/w220-h280-c6:7/wp-content/themes/ig/images/postpics/img_post_newtonwatch.jpg" alt="The Newton" />
		</div> <!-- END .RECARTICLE -->


		<div class="recarticle hover">
			<a class="reccomments" href="http://www.internetgentleman.com/tech/logitech-performance-mouse-mx/#comments" title="1 comment">1</a>

			<div class="title">
				<h3><a href="http://www.internetgentleman.com/tech/logitech-performance-mouse-mx/" title="Logitech Performance Mouse MX">Logitech Performance Mouse MX</a></h3>
			</div> <!-- END .TITLE -->

			<img src="/slir/w220-h280-c6:7/wp-content/themes/ig/images/postpics/img_post_logitechmx.jpg" alt="Logitech Performance Mouse MX" />
		</div> <!-- END .RECARTICLE -->


		<div class="recarticle hover">
			<a class="reccomments" href="http://www.internetgentleman.com/tech/snow-leopard/#comments" title="1 comment">1</a>

			<div class="title">
				<h3><a href="http://www.internetgentleman.com/tech/snow-leopard/" title="Snow Leopard OS X 10.6">Snow Leopard OS X 10.6</a></h3>
			</div> <!-- END .TITLE -->

			<img src="/slir/w220-h280-c6:7/wp-content/themes/ig/images/postpics/img_post_snowleopard.jpg" alt="Snow Leopard OS X 10.6" />
		</div> <!-- END .RECARTICLE -->


	</div> <!-- END #RECBOX -->

</div> <!-- END #RECOMMENDED -->
	</div> <!-- END WRAP -->

	<div id="footer" class="clear">

	<div id="footerwrap">

		<div id="about" class="footerbox">
			<h3 class="about"><span>Who Are You Guys?</span></h3>
			<p><strong>We offer the gentlemen of the internet a one-stop-shop for all things manly and modern.</strong> If you’d like to contact us, please feel free to drop us a line. And if you haven’t already, sign up for our newsletter for IG tips, tricks and deals.</p>
		</div> <!-- END #ABOUT -->

		<div id="categories" class="footerbox">
			<h3 class="categories"><span>Browse Categories</span></h3>
			<ul>
				<li class='hover' class="cat-item cat-item-5"><a href="http://www.internetgentleman.com/entertainment/" title="View all posts filed under Entertainment">Entertainment</a><span>13 items</span></li>	<li class='hover' class="cat-item cat-item-22"><a href="http://www.internetgentleman.com/libations/" title="View all posts filed under Libations">Libations</a><span>5 items</span></li>	<li class='hover' class="cat-item cat-item-13"><a href="http://www.internetgentleman.com/pad/" title="View all posts filed under Pad">Pad</a><span>18 items</span></li>	<li class='hover' class="cat-item cat-item-1"><a href="http://www.internetgentleman.com/style/" title="View all posts filed under Style">Style</a><span>20 items</span></li>	<li class='hover' class="cat-item cat-item-3"><a href="http://www.internetgentleman.com/tech/" title="View all posts filed under Tech">Tech</a><span>21 items</span></li>	<li class='hover' class="cat-item cat-item-18"><a href="http://www.internetgentleman.com/whips/" title="View all posts filed under Whips">Whips</a><span>4 items</span></li>
			</ul>
		</div> <!-- END #CATEGORIES -->

		<div id="twitter" class="footerbox">
			<h3 class="twitter"><span>Latest From Twitter</span></h3>
			<div class="twitterfeed"><a class="account" href="http://www.twitter.com/netgent" title="netgent">@netgent</a></div>
		</div>

		<div id="king" class="footerbox last">
			<h3 class="king"><span>Content Is King</span></h3>
			<p>Internet Gentleman is brought to you by the non-robotic content force commonly referred to as <a href="http://www.humanbinary.com" title="Human Binary">Human Binary</a>.</p>
			<p class="footerlinks">
				<a class="advertise" href="http://buysellads.com/buy/detail/11992" title="Advertise on IG"><span>Advertise on IG</span></a>
				<a class="feed" href="http://feeds.feedburner.com/InternetGentleman" title="Grab the Feed"><span>Grab the Feed</span></a>
			</p>
		</div> <!-- END #KING -->

		<div class="clear"> </div>

	</div> <!-- END #CONTENT -->

</div> <!-- END FOOTER -->

<div id="credits">

	<div class="creditcontainer">
		<p>Copyright &copy; 2009 <a class="hb" href="http://www.humanbinary.com" title="Human Binary"><span class="h">H</span><span class="u">u</span><span class="m">m</span><span class="a">a</span><span class="n">n</span> Binary</a> <span>Network</span>. All rights reserved.</p>

		<p class="terms"><a href="http://www.internetgentleman.com/terms-of-use" title="Terms of Use">Terms of Use</a>&nbsp;&nbsp;&nbsp;<a href="http://www.internetgentleman.com/privacy-policy" title="Privacy Policy">Privacy Policy</a></p>

		<p class="built"><span class="fortyfive">Site designed and built by <a href="http://www.45royale.com" title="45royale Inc">45royale Inc.</a></span></p>
	</div> <!-- END .CREDITCONTAINER -->
</div> <!-- END #CREDITS -->

<!-- GLOBAL JAVASCRIPT -->
	<script type="text/javascript" src="http://www.internetgentleman.com/wp-content/themes/ig/js/jquery.tools.min.js"> </script>
	<script type="text/javascript" src="http://www.internetgentleman.com/wp-content/themes/ig/js/global.js"> </script>
	<script type="text/javascript" src="http://www.internetgentleman.com/wp-content/themes/ig/js/css_browser_selector.js"> </script>
	<script type="text/javascript" src="http://www.internetgentleman.com/wp-content/themes/ig/js/jquery.twitter.js"> </script>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-10017408-1");
pageTracker._trackPageview();
} catch(err) {}</script>


</body>

</html>
